name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - if: runner.os == 'linux'
        name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: clippy
        run: cargo clippy --workspace --all-targets --verbose -- -D warnings
      - name: build
        run: cargo build --workspace --all-targets --verbose
      - name: test
        run: cargo test --workspace --all-targets --verbose

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: fmt
        run: cargo +nightly fmt --all --check
